#this is  comment

apiVersion: v1
kind: Pod
metadata:
  name: ngnix-pod
  labels:
    env: demo
    type: frontend
spec:
  containers:
   - name: nginx-container
     image: ngnix
     ports:
      - containerPort: 80
      the actuall thing is to aggresively code the actuall things ijn this manner 

and the actuall thing is the dockrize file to be obsseed with each file wihch is given overhere